export interface ProductCategory {
  id: string;
  name: string;
  description: string;
  sortOrder: number;
}

export interface Product {
  id: string;
  name: string;
  categoryId: string;
  price: number;
  image: string;
  description: string;
  size?: string;
  isBestSeller?: boolean;
  isNew?: boolean;
  isActive?: boolean;
}

export const defaultCategories: ProductCategory[] = [
  { id: 'parfait', name: 'Parfait 330ml', description: 'Layered cups and chilled favorites', sortOrder: 1 },
  { id: 'yoghurt', name: 'Yoghurt', description: 'Fresh yoghurt bottles in multiple sizes', sortOrder: 2 },
  { id: 'pastries', name: 'Pastries & Snacks', description: 'Savory and sweet bakery picks', sortOrder: 3 },
  { id: 'cakes', name: 'Cakes', description: 'Premium celebration cakes inspired by Lagos luxury dessert pricing', sortOrder: 4 },
  { id: 'zobo', name: 'Zobo', description: 'Refreshing hibiscus drinks', sortOrder: 5 },
  { id: 'tiger-nut', name: 'Tiger Nut Drink', description: 'Creamy local drink options', sortOrder: 6 },
  { id: 'only-food', name: 'Meals & Soups', description: 'Meals and soup selections', sortOrder: 7 },
];

export const defaultProducts: Product[] = [
  {
    id: 'parfait-1',
    name: 'Fruit Parfait 330ml',
    categoryId: 'parfait',
    price: 3000,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663417086272/fTUGaCUm9YQhQkvWWi8FLU/parfait-plain-fruit-sticker-RwC2BsoncfSGTeEgmVkN92.webp',
    description: 'Creamy fruit parfait layered with berries and crunchy granola.',
    size: '330ml',
    isBestSeller: true,
    isActive: true,
  },
  {
    id: 'parfait-2',
    name: 'Cake Parfait 330ml',
    categoryId: 'parfait',
    price: 3900,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663417086272/fTUGaCUm9YQhQkvWWi8FLU/parfait-cake-sticker-NpSP9LxRGxUMBpd8aoKQYP.webp',
    description: 'Vanilla cake layers, whipped cream, and chocolate shavings in a chilled cup.',
    size: '330ml',
    isNew: true,
    isActive: true,
  },
  {
    id: 'parfait-3',
    name: 'Strawberry Fruit Parfait 330ml',
    categoryId: 'parfait',
    price: 3000,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663417086272/fTUGaCUm9YQhQkvWWi8FLU/parfait-strawberry-sticker-ZUuz5AytiW9mYuKGJzZAbX.webp',
    description: 'Strawberry-flavored parfait finished with fresh fruit notes and granola.',
    size: '330ml',
    isActive: true,
  },
  {
    id: 'parfait-4',
    name: 'Banana Fruit Parfait 330ml',
    categoryId: 'parfait',
    price: 3000,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663417086272/fTUGaCUm9YQhQkvWWi8FLU/parfait-banana-sticker-4SnP4L7nS57YoKavxn8S7R.webp',
    description: 'Banana parfait with smooth cream layers and a balanced sweetness.',
    size: '330ml',
    isActive: true,
  },
  {
    id: 'parfait-5',
    name: 'Vanilla Fruit Parfait 330ml',
    categoryId: 'parfait',
    price: 3000,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663417086272/fTUGaCUm9YQhQkvWWi8FLU/parfait-vanilla-sticker-jg9ouoCCfoBQRpdpRnr2fe.webp',
    description: 'Vanilla parfait with mixed berries and honey granola.',
    size: '330ml',
    isActive: true,
  },
  {
    id: 'yoghurt-1',
    name: 'Plain Sweetened Yoghurt 35cl',
    categoryId: 'yoghurt',
    price: 2500,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663417086272/fTUGaCUm9YQhQkvWWi8FLU/yoghurt-plain-sweetened-sticker-CxWrEpqLqiZZrsmzMN6CQV.webp',
    description: 'Smooth bottled yoghurt with a clean, creamy finish.',
    size: '35cl',
    isActive: true,
  },
  {
    id: 'pastries-1',
    name: 'Chin-Chin Pack',
    categoryId: 'pastries',
    price: 1500,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663417086272/fTUGaCUm9YQhQkvWWi8FLU/pastries-assorted-sticker-jYnFRiFeRf22VwuRZ3kHHu.webp',
    description: 'Crunchy chin-chin with the rich golden finish customers expect.',
    isBestSeller: true,
    isActive: true,
  },
  {
    id: 'pastries-2',
    name: 'Fish Pie',
    categoryId: 'pastries',
    price: 2000,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663417086272/fTUGaCUm9YQhQkvWWi8FLU/pastries-assorted-sticker-jYnFRiFeRf22VwuRZ3kHHu.webp',
    description: 'Flaky fish pie baked with a savory Nigerian-style filling.',
    isActive: true,
  },
  {
    id: 'pastries-3',
    name: 'Meat Pie',
    categoryId: 'pastries',
    price: 2000,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663417086272/fTUGaCUm9YQhQkvWWi8FLU/pastries-assorted-sticker-jYnFRiFeRf22VwuRZ3kHHu.webp',
    description: 'Classic meat pie with a buttery crust and seasoned filling.',
    isActive: true,
  },
  {
    id: 'pastries-4',
    name: 'Chicken Pie',
    categoryId: 'pastries',
    price: 2000,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663417086272/fTUGaCUm9YQhQkvWWi8FLU/pastries-assorted-ZZuQdsLFWJAeVepJrUMhQD.webp',
    description: 'Tender chicken pie with a flaky, golden pastry shell.',
    isActive: true,
  },
  {
    id: 'pastries-5',
    name: 'Doughnut',
    categoryId: 'pastries',
    price: 1500,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663417086272/fTUGaCUm9YQhQkvWWi8FLU/pastries-assorted-ZZuQdsLFWJAeVepJrUMhQD.webp',
    description: 'Soft doughnut with a clean finish and light sugar coating.',
    isActive: true,
  },
  {
    id: 'pastries-6',
    name: 'Puff-Puff Pack',
    categoryId: 'pastries',
    price: 1500,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663417086272/fTUGaCUm9YQhQkvWWi8FLU/pastries-assorted-ZZuQdsLFWJAeVepJrUMhQD.webp',
    description: 'Soft, airy puff-puff with the golden look common in Nigerian snack spots.',
    isBestSeller: true,
    isActive: true,
  },
  {
    id: 'pastries-7',
    name: 'Shawarma',
    categoryId: 'pastries',
    price: 2500,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663417086272/fTUGaCUm9YQhQkvWWi8FLU/pastries-assorted-ZZuQdsLFWJAeVepJrUMhQD.webp',
    description: 'Loaded shawarma with grilled filling, vegetables, and creamy sauce.',
    isActive: true,
  },
  {
    id: 'cakes-1',
    name: 'Vanilla Buttercream Cake',
    categoryId: 'cakes',
    price: 45000,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663417086272/fTUGaCUm9YQhQkvWWi8FLU/cake-vanilla-sticker-UBtgsBfBka9yAbjJsXGyMq.webp',
    description: 'Premium 8-inch vanilla buttercream cake for birthdays and intimate celebrations.',
    size: '8 inch',
    isBestSeller: true,
    isActive: true,
  },
  {
    id: 'cakes-2',
    name: 'Chocolate Celebration Cake',
    categoryId: 'cakes',
    price: 50000,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663417086272/fTUGaCUm9YQhQkvWWi8FLU/cake-vanilla-fpHHGRZCjgFBZLXMAVy6ZX.webp',
    description: 'Premium chocolate cake styled for Lagos event gifting and small celebrations.',
    size: '8 inch',
    isActive: true,
  },
  {
    id: 'cakes-3',
    name: 'Red Velvet Cream Cheese Cake',
    categoryId: 'cakes',
    price: 78000,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663417086272/fTUGaCUm9YQhQkvWWi8FLU/cake-vanilla-fpHHGRZCjgFBZLXMAVy6ZX.webp',
    description: 'Luxury red velvet celebration cake with cream cheese styling, priced in line with premium Lekki and Ikoyi cake positioning.',
    size: '8 inch',
    isNew: true,
    isActive: true,
  },
  {
    id: 'zobo-1',
    name: 'Zobo Drink 35cl',
    categoryId: 'zobo',
    price: 1500,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663417086272/fTUGaCUm9YQhQkvWWi8FLU/zobo-drink-sticker-bFuXKBRaP2omb5p5MJz9zg.webp',
    description: 'Fresh hibiscus zobo in a bottle with a bold Nigerian taste profile.',
    size: '35cl',
    isActive: true,
  },
  {
    id: 'zobo-2',
    name: 'Zobo Drink 30cl',
    categoryId: 'zobo',
    price: 1200,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663417086272/fTUGaCUm9YQhQkvWWi8FLU/zobo-drink-jYEddzskMqGkKr6KaAoWP2.webp',
    description: 'Compact zobo bottle for quick refreshment and easy delivery.',
    size: '30cl',
    isActive: true,
  },
  {
    id: 'tiger-nut-1',
    name: 'Tiger Nut Drink 35cl',
    categoryId: 'tiger-nut',
    price: 2000,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663417086272/fTUGaCUm9YQhQkvWWi8FLU/tiger-nut-drink-sticker-U2VPLDvKC2LWYg5eJKETQZ.webp',
    description: 'Creamy tiger nut drink with the rich texture people expect from local premium vendors.',
    size: '35cl',
    isActive: true,
  },
  {
    id: 'tiger-nut-2',
    name: 'Tiger Nut Drink 30cl',
    categoryId: 'tiger-nut',
    price: 1700,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663417086272/fTUGaCUm9YQhQkvWWi8FLU/zobo-drink-jYEddzskMqGkKr6KaAoWP2.webp',
    description: 'Chilled tiger nut drink in a compact bottle size.',
    size: '30cl',
    isActive: true,
  },
  {
    id: 'only-food-1',
    name: 'Jollof Rice Tray',
    categoryId: 'only-food',
    price: 3500,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663417086272/fTUGaCUm9YQhQkvWWi8FLU/jollof-rice-sticker-P5rCN9yzKReiUjTwn95NV6.webp',
    description: 'Smoky party-style jollof rice served the way Nigerian customers expect.',
    isBestSeller: true,
    isActive: true,
  },
  {
    id: 'only-food-2',
    name: 'Fried Rice Tray',
    categoryId: 'only-food',
    price: 3500,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663417086272/fTUGaCUm9YQhQkvWWi8FLU/jollof-rice-Lb9uv6um8SpqJHjB2vv59F.webp',
    description: 'Colorful fried rice with vegetables and a party-style finish.',
    isActive: true,
  },
  {
    id: 'only-food-3',
    name: 'Coconut Rice Tray',
    categoryId: 'only-food',
    price: 3500,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663417086272/fTUGaCUm9YQhQkvWWi8FLU/jollof-rice-Lb9uv6um8SpqJHjB2vv59F.webp',
    description: 'Coconut rice with a rich aroma and soft, flavorful grains.',
    isActive: true,
  },
  {
    id: 'only-food-4',
    name: 'Egusi Soup Bowl',
    categoryId: 'only-food',
    price: 4000,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663417086272/fTUGaCUm9YQhQkvWWi8FLU/egusi-soup-sticker-XzPfCHQQ2yhuM2dppNJ4zv.webp',
    description: 'Rich egusi soup with vegetables and assorted protein.',
    isActive: true,
  },
  {
    id: 'only-food-5',
    name: 'Ogbono Soup Bowl',
    categoryId: 'only-food',
    price: 3000,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663417086272/fTUGaCUm9YQhQkvWWi8FLU/jollof-rice-Lb9uv6um8SpqJHjB2vv59F.webp',
    description: 'Smooth ogbono soup prepared with a rich Nigerian flavor base.',
    isActive: true,
  },
  {
    id: 'only-food-6',
    name: 'Editan Soup Bowl',
    categoryId: 'only-food',
    price: 2800,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663417086272/fTUGaCUm9YQhQkvWWi8FLU/jollof-rice-Lb9uv6um8SpqJHjB2vv59F.webp',
    description: 'Traditional editan soup finished with a rich local seasoning profile.',
    isActive: true,
  },
  {
    id: 'only-food-7',
    name: 'Afang Soup Bowl',
    categoryId: 'only-food',
    price: 3000,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663417086272/fTUGaCUm9YQhQkvWWi8FLU/jollof-rice-Lb9uv6um8SpqJHjB2vv59F.webp',
    description: 'Afang soup with seafood and meat for a fuller restaurant-style portion.',
    isActive: true,
  },
  {
    id: 'only-food-8',
    name: 'Okro Soup Bowl',
    categoryId: 'only-food',
    price: 2800,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663417086272/fTUGaCUm9YQhQkvWWi8FLU/jollof-rice-Lb9uv6um8SpqJHjB2vv59F.webp',
    description: 'Okro soup with a hearty mix of meat and fish.',
    isActive: true,
  },
  {
    id: 'only-food-9',
    name: 'White Soup Bowl',
    categoryId: 'only-food',
    price: 3200,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663417086272/fTUGaCUm9YQhQkvWWi8FLU/jollof-rice-Lb9uv6um8SpqJHjB2vv59F.webp',
    description: 'White soup with a creamy body and bright traditional spice notes.',
    isActive: true,
  },
  {
    id: 'only-food-10',
    name: 'Goat Meat Pepper Soup',
    categoryId: 'only-food',
    price: 3500,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663417086272/fTUGaCUm9YQhQkvWWi8FLU/jollof-rice-Lb9uv6um8SpqJHjB2vv59F.webp',
    description: 'Hot goat meat pepper soup with a proper restaurant-style spice blend.',
    isActive: true,
  },
  {
    id: 'only-food-11',
    name: 'Chicken Pepper Soup',
    categoryId: 'only-food',
    price: 3000,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663417086272/fTUGaCUm9YQhQkvWWi8FLU/jollof-rice-Lb9uv6um8SpqJHjB2vv59F.webp',
    description: 'Chicken pepper soup prepared for a bold, warming finish.',
    isActive: true,
  },
  {
    id: 'only-food-12',
    name: 'Efirin Vegetable Soup Bowl',
    categoryId: 'only-food',
    price: 2800,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663417086272/fTUGaCUm9YQhQkvWWi8FLU/jollof-rice-Lb9uv6um8SpqJHjB2vv59F.webp',
    description: 'Vegetable soup with scent leaf and a rich local flavor base.',
    isActive: true,
  },
];
